# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Microkai"
license = "MIT"
licenselink = "https://github.com/oppenbhaimer/microkai/blob/main/LICENSE"
description = "Lightweight monokai theme for the web"
homepage = "https://github.com/oppenbhaimer/microkai/"
demosite = "https://oppenbhaimer.github.io/microkai"
tags = ["Responsive", "Simple", "Clean", "Light", "Blog"]
features = ["Responsive", "One Column", "Blog"]
min_version = "0.57.1"

[author]
  name = "oppenbhaimer"
  homepage = "https://oppenbhaimer.github.io/"
